In [14]:
%run "../../PyUtils/common.ipynb"

f1="P1_HanD_Ver1_2015_15122015_PMPEF.xlsx"
df1 = LoadDataSet(f1, sheetname=2);
#f1="P1_HanD_Ver1_2015_22112015_AMPEF.xlsx";
#dfOrginal1 = LoadDataSet(f1);
df1=df1[11:]


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [17]:
df1[108:]

Unnamed: 0           Unnamed: 1 Unnamed: 2           Unnamed: 3 Unnamed: 4           Unnamed: 5           Unnamed: 6 Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10 Unnamed: 11 Unnamed: 12 Unnamed: 13 Unnamed: 14 Unnamed: 15 Unnamed: 16 Unnamed: 17 Unnamed: 18 Unnamed: 19 Unnamed: 20 Unnamed: 21 Unnamed: 22 Unnamed: 23 Unnamed: 24 Unnamed: 25 Unnamed: 26 Unnamed: 27  Unnamed: 28 Unnamed: 29 Unnamed: 30 Unnamed: 31          Unnamed: 32
119        109  2015-04-19 00:00:00          0  2015-04-18 00:00:00   18:47:00  2015-04-19 00:00:00  2016-12-14 18:20:00        NaN      0.103     17.300       0.344       1.134         928      19.700    1008.800         100          12     999.800          27      14.600    1007.700         100       7.700           9          73      14.600     999.800         100          nan           1         248           Y  2015-04-19 00:00:00
120        110  2015-04-20 00:00:00          1  2015-04-19 00:00:00   18:20:00  2015-04-20 00:00:00             18:27:00        NaN      0.063     11.700       0.848       0.591         268      16.500    1004.900         100      11.300     998.700          52      11.600    1000.500          98       5.200       6.200          48          16    1004.900          53          nan           1         277           Y  2015-04-20 00:00:00
121        111  2015-04-21 00:00:00          2  2015-04-20 00:00:00   18:27:00  2015-04-21 00:00:00             19:05:00        NaN      0.135     15.600       0.604       0.980         886      20.900    1012.500         100       6.200    1005.600          19       7.300    1009.700         100      14.700       6.900          81      14.800    1011.600          33          nan           1         262           Y  2015-04-21 00:00:00
122        112  2015-04-22 00:00:00          3  2015-04-21 00:00:00   19:05:00  2015-04-22 00:00:00             18:28:00        NaN      0.159     14.700       1.096       0.715        1533      19.400    1014.400          66       7.700    1012.600          36       8.300    1013.800          47      11.700       1.800          30      16.400    1014.300          53          nan           1         263           Y  2015-04-22 00:00:00
..         ...                  ...        ...                  ...        ...                  ...                  ...        ...        ...        ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...         ...          ...         ...         ...         ...                  ...
372        362  2015-12-28 00:00:00          1  2015-12-27 00:00:00   18:15:00  2015-12-28 00:00:00             18:05:00        NaN      0.106         12       0.389       0.429         768       0.400    1030.400          66      -8.400    1027.900          21      -7.900        1029          35       8.800       2.500          45      -2.200    1029.100          28          nan           4         240           Y  2015-12-28 00:00:00
373        363  2015-12-29 00:00:00          2  2015-12-28 00:00:00   18:05:00  2015-12-29 00:00:00             18:05:00        NaN      0.150     20.200       0.116       0.857        1366       2.700    1030.900          77      -9.100        1028          32      -6.700    1030.100          43      11.800       2.900          45       0.700    1028.300          54          nan           4         243           Y  2015-12-29 00:00:00
374        364  2015-12-30 00:00:00          3  2015-12-29 00:00:00   18:05:00  2015-12-30 00:00:00             18:12:00        NaN      0.173     23.200       0.100       1.073        1714       5.700    1028.200          89      -2.900    1022.200          47      -0.900    1027.900          50       8.600           6          42       2.600    1023.100          89          nan           4         238           Y  2015-12-30 00:00:00
375        365  2015-12-31 00:00:00         

In [35]:
X=np.random.rand(6,3)
y=np.random.rand(6,1)
from sklearn.model_selection import KFold

kf = KFold(n_splits=5)

for train_index, test_index in kf.split(X):
    X_train, X_test = X[train_index], X[test_index]
    y_train = y[train_index]
    #
    #print (X_train, y_train)
    print (train_index, test_index)

[2 3 4 5] [0 1]
[0 1 3 4 5] [2]
[0 1 2 4 5] [3]
[0 1 2 3 5] [4]
[0 1 2 3 4] [5]


In [40]:
kf = sklearn.cross_validation.KFold(len(y),n_folds=5,shuffle=True)
y_pred = y.copy()

# Iterate through folds\
i = 0;
for train_index, test_index in kf:
    X_train, X_test = X[train_index], X[test_index]
    y_train = y[train_index]
    
    print (X_train, y_train)
    #print (train_index, test_index)

[[ 0.26  0.49  0.53]
 [ 0.11  0.21  0.34]
 [ 0.47  0.73  0.72]
 [ 0.28  0.69  0.06]] [[ 0.37]
 [ 0.63]
 [ 0.63]
 [ 0.08]]
[[ 0.26  0.49  0.53]
 [ 0.11  0.21  0.34]
 [ 0.73  0.23  0.45]
 [ 0.83  0.86  0.93]
 [ 0.28  0.69  0.06]] [[ 0.37]
 [ 0.63]
 [ 0.31]
 [ 0.9 ]
 [ 0.08]]
[[ 0.26  0.49  0.53]
 [ 0.73  0.23  0.45]
 [ 0.83  0.86  0.93]
 [ 0.47  0.73  0.72]
 [ 0.28  0.69  0.06]] [[ 0.37]
 [ 0.31]
 [ 0.9 ]
 [ 0.63]
 [ 0.08]]
[[ 0.26  0.49  0.53]
 [ 0.11  0.21  0.34]
 [ 0.73  0.23  0.45]
 [ 0.83  0.86  0.93]
 [ 0.47  0.73  0.72]] [[ 0.37]
 [ 0.63]
 [ 0.31]
 [ 0.9 ]
 [ 0.63]]
[[ 0.11  0.21  0.34]
 [ 0.73  0.23  0.45]
 [ 0.83  0.86  0.93]
 [ 0.47  0.73  0.72]
 [ 0.28  0.69  0.06]] [[ 0.63]
 [ 0.31]
 [ 0.9 ]
 [ 0.63]
 [ 0.08]]
